'use client';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import { type Snapshot } from '../../lib/model';
import { ActivityRows,Empty,formatDate,HealthTable,Section,State } from '../primitives';
export function Automations({data}:{data:Snapshot}) {
  const id=useSearchParams().get('intake');const intake=data.intakes.find(i=>i.id===id);
  return <><div className="inline-note">State is derived from persistent records. “Observed” means a successful record exists; it does not certify scheduler or provider availability. Latency is unmeasured.</div><Section title="Logical services" meta={<span className="section-meta">Full database aggregates</span>}><HealthTable services={data.services??[]}/></Section>
    {intake&&<Section title={`Intake #${intake.number}`} meta={<Link href="/automations" className="text-link">Clear selection</Link>}><div className="intake-context"><strong>{intake.summary??'Awaiting structured details'}</strong><State value={intake.state}/><time>{formatDate(intake.updatedAt)}</time></div>{data.interactions.filter(i=>i.intakeId===id&&i.status==='open').map(i=><div className="operator-instruction" key={i.id}>{i.kind.replaceAll('_',' ')} required. Reply to the correlated prompt in the existing Telegram operator conversation.</div>)}</Section>}
    <div className="automation-panes"><Section title="Operator interactions"><div className="table-scroll"><table className="data-table"><thead><tr><th>Intake</th><th>Input</th><th>State</th><th>Opened</th><th>Resolved</th></tr></thead><tbody>{data.interactions.map(i=><tr key={i.id}><td><Link href={`/automations?intake=${i.intakeId}`}>#{data.intakes.find(x=>x.id===i.intakeId)?.number??'unavailable'}</Link></td><td>{i.kind.replaceAll('_',' ')}</td><td><State value={i.status}/></td><td className="mono nowrap">{formatDate(i.createdAt)}</td><td className="mono nowrap">{formatDate(i.resolvedAt)}</td></tr>)}</tbody></table></div>{!data.interactions.length&&<Empty title="No interactions" detail="No operator requests were returned."/>}</Section><Section title="Intake state"><div className="table-scroll"><table className="data-table"><thead><tr><th>Intake</th><th>Summary</th><th>State</th></tr></thead><tbody>{data.intakes.map(i=><tr key={i.id} className={i.id===id?'selected-row':''}><td><Link href={`/automations?intake=${i.id}`}>#{i.number}</Link></td><td>{i.summary??'Awaiting extraction'}</td><td><State value={i.state}/></td></tr>)}</tbody></table></div></Section></div>
    <details className="admin-details"><summary>Technical drilldown · read-only work and delivery records</summary><div className="automation-panes"><Section title="Work items"><table className="data-table"><thead><tr><th>Stage</th><th>State</th><th>Attempts</th><th>Last update</th></tr></thead><tbody>{data.work.map(w=><tr key={w.id}><td>{w.stage}</td><td><State value={w.status}/></td><td>{w.attempts}/{w.maxAttempts}</td><td className="mono nowrap">{formatDate(w.updatedAt)}</td></tr>)}</tbody></table></Section><Section title="Outbox"><table className="data-table"><thead><tr><th>Kind</th><th>Delivery state</th><th>Attempts</th></tr></thead><tbody>{data.deliveries.map(d=><tr key={d.id}><td>{d.kind}</td><td><State value={d.status}/></td><td>{d.attempts}</td></tr>)}</tbody></table></Section></div></details><Section title="Latest recorded events"><ActivityRows events={data.activity??[]} limit={20}/></Section></>;
}
